spring:
  bot:
    plugin-list: # 配置插件列表（有序），如果插件返回0，继续执行剩余插件，如果插件返回1，终止剩余插件执行
      - net.xinmu.pbbot.plugin.LogPlugin # 日志插件
#     - net.xinmu.pbbot.plugin.DemoPlugin # 测试插件
#     - net.xinmu.pbbot.plugin.ImagePlugin # 动态生成图片插件
#     - net.xinmu.pbbot.plugin.HelloPlugin # 测试插件
      - net.xinmu.pbbot.plugin.DianGePlugin #多功能插件
      - net.xinmu.pbbot.plugin.LiaoTianPlugin #聊天机器人插件

server:
  port: 8081